---
- name: Set the hostname in /etc/hostname
  lineinfile: dest=/etc/hostname line="{{ remote.hostname }}"
  register: added_hostname

- name: Set the hostname
  shell: hostname {{ remote.hostname }}
  when: added_hostname == True

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ remote.hostname }}' owner=root group=root mode=0644

- name: Add default index
  copy: src=index.html dest=/usr/share/nginx/html/

- name: Add OPcache reset
  copy: src=iFEzvlepqNf.php dest=/usr/share/nginx/html/

- name: Add web group
  group: name=web state=present

- name: Add dev user
  user: name={{ remote.user }} comment="Development user" group={{ remote.group }}

- name: Add dev user umask
  lineinfile: dest=/home/{{ remote.user }}/.bashrc line="umask 0002"

- include: project.yml
